// src/media-picker.jsx
/* eslint-disable jsx/no-undef */
import { onCleanup, createState } from 'solid-js';
import { createRecorder } from './media-lib';

function LiveVid(p) {
  return (
    <div class="quikpik-vid-wrapper">
      <video
        class="quikpik-vid"
        srcObject={p.recorder.liveSrc()}
        muted={true}
        controls={false}
        autoplay="true"
      ></video>
    </div>
  );
}

function computeElapsedTime(startTime) {
  const elapsedMs = Date.now() - startTime;
  const sec = Math.floor(elapsedMs / 1000) % 60;
  const min = Math.floor(sec / 60) % 60;
  const h = Math.floor(min / 60);

  return `${h ? h + ':' : ''}${min.toString().padStart(2, '0')}:${sec.toString().padStart(2, '0')}`;
}

function ElapsedTime() {
  const startTime = Date.now();

  const [state, setState] = createState({
    elapsedTime: computeElapsedTime(startTime),
  });

  let timeout = setTimeout(function tick() {
    if (!timeout) {
      return;
    }

    setState((s) => ({ ...s, elapsedTime: computeElapsedTime(startTime) }));
    timeout = setTimeout(tick, 1000);
  }, 1000);

  onCleanup(() => {
    clearTimeout(timeout);
    timeout = undefined;
  });

  return (
    <span class="quikpik-elapsed-time">
      <style jsx global>
        {`
          .quikpik-elapsed-time {
            position: absolute;
            left: calc(50% + 2.75rem);
            top: 50%;
            margin-top: -0.5rem;
            line-height: 1;
            opacity: 0.8;
          }
        `}
      </style>
      Recording {state.elapsedTime}
    </span>
  );
}

function ConfirmMedia(p) {
  const src = URL.createObjectURL(p.file);

  onCleanup(() => URL.revokeObjectURL(src));

  if (p.file.type.startsWith('video/') || p.file.type.startsWith('audio/')) {
    return (
      <div class="quikpik-vid-wrapper">
        <video class="quikpik-vid" src={src} muted={false} controls={true}></video>
      </div>
    );
  }

  return (
    <div class="quikpik-confirm-wrapper">
      <img class="quikpik-confirm-item" src={src} ref="Your photo" />
    </div>
  );
}

/**
 * Generic media picker UI
 * @param {object} p
 * @param {takephoto | takevideo | takeaudio} mode
 * @param {(f: file) => { promise: Promise, cancel: () => void }} p.uploadFile
 */
export function MediaPicker(p) {
  const [state, setState] = createState({
    // init | error | live | recording | confirm
    mode: 'init',

    // The error message to be displayed.
    error: undefined,

    // The media recorder resulting from createRecorder
    recorder: undefined,

    // The captured file
    file: undefined,
  });

  const recorderOpts =
    p.mode === 'takephoto'
      ? { video: true }
      : p.mode === 'takeaudio'
      ? { audio: true }
      : { video: true, audio: true };

  function mediaError(err) {
    console.error(err);
    setState((s) => ({ ...s, mode: 'error', error: 'Unable to connect to your camera.' }));
  }

  function retake() {
    setState((s) => ({ ...s, mode: 'live', file: undefined }));
  }

  function upload() {
    p.uploadFile(state.file);
  }

  function captureImage() {
    state.recorder
      .capturePhoto()
      .then((file) => setState((s) => ({ ...s, mode: 'confirm', file })))
      .catch(mediaError);
  }

  function startRecording() {
    state.recorder.beginMediaCapture();
    setState((s) => ({ ...s, mode: 'recording' }));
  }

  function stopRecording() {
    state.recorder
      .endMediaCapture()
      .then((file) => setState((s) => ({ ...s, mode: 'confirm', file })))
      .catch(mediaError);
  }

  function onCapture() {
    if (p.mode === 'takephoto') {
      captureImage();
    } else {
      startRecording();
    }
  }

  createRecorder(recorderOpts)
    .then((recorder) => setState((s) => ({ ...s, mode: 'live', recorder })))
    .catch(mediaError);

  return (
    <div class="quikpik-photo">
      <style jsx global>
        {`
          .quikpik-photo {
            box-sizing: border-box;
            flex-grow: 1;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            background: #1a202c;
            color: #fff;
            padding: 1rem;
            border-radius: 0.375rem;
          }

          .quikpik-vid-wrapper {
            flex-grow: 1;
          }

          .quikpik-info {
            color: #6b7280;
          }

          .quikpik-media-footer {
            position: relative;
            padding: 1rem;
            width: 100%;
          }

          .quikpik-vid-wrapper {
            position: relative;
            width: 100%;
            flex-grow: 1;
          }

          .quikpik-vid {
            position: absolute;
            height: 100%;
            width: 100%;
            margin: auto;
            left: 50%;
            transform: translateX(-50%);
            border-radius: 2px;
            outline: none;
          }

          .quikpik-snap-photo {
            background: #fff;
            cursor: pointer;
            box-shadow: inset 0 0 0 2px;
            border: 4px solid #fff;
            width: 3rem;
            height: 3rem;
            border-radius: 100%;
            outline: none;
          }

          .quikpik-stop-media,
          .quikpik-record-media {
            position: relative;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            background: #f00;
            box-shadow: inset 0 0 0 2px;
            border: 4px solid #fff;
            width: 3rem;
            height: 3rem;
            border-radius: 100%;
            outline: none;
          }

          .quikpik-stop-media {
            background: transparent;
          }

          .quikpik-stop-media::before {
            content: '';
            background: #f00;
            height: 1.5rem;
            width: 1.5rem;
            border-radius: 2px;
          }

          .quikpik-snap-photo:focus {
            box-shadow: inset 0 0 0 4px;
          }

          .quikpik-media-retake,
          .quikpik-media-accept {
            background: #5a67d8;
            color: #fff;
            border: 0;
            padding: 0.5rem 0.75rem;
            font-size: 0.875rem;
            border-radius: 0.375rem;
            cursor: pointer;
            margin: 0 0.25rem;
            outline: none;
          }

          .quikpik-media-retake {
            border: 1px solid;
            background: transparent;
            color: inherit;
          }

          .quikpik-confirm-item {
            width: 100%;
            max-width: 100%;
            max-height: 100%;
          }
        `}
      </style>
      {state.mode === 'error' && <p class="quikpik-error">{state.error}</p>}
      {state.mode === 'init' && <p class="quikpik-info">Connecting to your camera...</p>}
      {(state.mode === 'live' || state.mode === 'recording') && (
        <LiveVid recorder={state.recorder} />
      )}
      {state.mode === 'live' && (
        <footer class="quikpik-media-footer">
          <button
            class="quikpik-snap-photo"
            classList={{
              'quikpik-record-media': p.mode !== 'takephoto',
              'quikpik-stop-media': state.mode === 'recording',
            }}
            onClick={onCapture}
          ></button>
        </footer>
      )}
      {state.mode === 'recording' && (
        <footer class="quikpik-media-footer">
          <button class="quikpik-stop-media" onClick={stopRecording}></button>
          <ElapsedTime />
        </footer>
      )}
      {state.mode === 'confirm' && <ConfirmMedia file={state.file} />}
      {state.mode === 'confirm' && (
        <footer class="quikpik-media-footer">
          <button class="quikpik-media-retake" onClick={retake}>
            Retake
          </button>
          <button class="quikpik-media-accept" onClick={upload}>
            Accept &amp; upload
          </button>
        </footer>
      )}
    </div>
  );
}

// lib/media-picker.svelte
<script>
  import { onMount } from 'svelte';
  import LiveVid from './live-vid.svelte';
  import ElapsedTime from './elapsed-time.svelte';
  import ConfirmMedia from './confirm-media.svelte';
  import { createRecorder } from './media-lib';

  export let mode;
  export let uploadFile;

  // init | live | error | recording | confirm
  let status = 'init';
  let error;
  let recorder;
  let recorderMode;
  let file;

  $: recorderOpts = { video: mode !== 'takeaudio', audio: true };
  $: recorderPromise = createRecorder(recorderOpts)
    .then((value) => {
      recorder = value;
      status = 'live';
      recorderMode = mode;
    })
    .catch(mediaError);

  function mediaError(err) {
    console.error(err);
    status = 'error';
    error = 'Unable to connect to your camera.';
  }

  function captureImage() {
    recorder
      .capturePhoto()
      .then((newFile) => {
        file = newFile;
        status = 'confirm';
      })
      .catch(mediaError);
  }

  function startRecording() {
    recorder.beginMediaCapture();
    status = 'recording';
  }

  function onCapture() {
    if (mode === 'takephoto') {
      captureImage();
    } else {
      startRecording();
    }
  }

  function stopRecording() {
    recorder
      .endMediaCapture()
      .then((newFile) => {
        file = newFile;
        status = 'confirm';
      })
      .catch(mediaError);
  }

  function retake() {
    status = 'live';
    file = undefined;
  }

  function accept() {
    uploadFile(file);
  }
</script>

<div class="quikpik-media">
  {#if status === 'error'}
    <p class="quikpik-error">{error}</p>
  {/if}
  {#if status === 'init'}
    <p class="quikpik-info">Waiting for your camera or microphone to be ready.</p>
  {/if}
  {#if (status === 'live' || status === 'recording') && mode !== 'takeaudio'}
    <LiveVid recorder={recorder} />
  {/if}
  {#if (status === 'live' && mode === 'takeaudio')}
    <p class="quikpik-info">Click the red button to begin recording.</p>
  {/if}
  {#if status === 'live'}
    <footer class="quikpik-media-footer">
      <button
        class="quikpik-snap-photo"
        class:quikpik-record-media={mode !== 'takephoto'}
        class:quikpik-stop-media={status === 'recording'}
        disabled={recorderMode !== mode}
        on:click={onCapture}
      ></button>
    </footer>
  {/if}
  {#if status === 'recording'}
    <footer class="quikpik-media-footer">
      <button class="quikpik-stop-media" on:click={stopRecording}></button>
      <ElapsedTime />
    </footer>
  {/if}
  {#if status === 'confirm'}
    <ConfirmMedia file={file} />
    <footer class="quikpik-media-footer">
      <button class="quikpik-media-retake" on:click={retake}>
        Retake
      </button>
      <button class="quikpik-media-accept" on:click={accept}>
        Accept &amp; upload
      </button>
    </footer>
  {/if}
</div>

<style>
  .quikpik-media {
    box-sizing: border-box;
    flex-grow: 1;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    background: #1a202c;
    color: #fff;
    padding: 1rem;
    border-radius: 0.375rem;
  }

  .quikpik-media-footer {
    position: relative;
    padding: 1rem;
    width: 100%;
  }

  .quikpik-snap-photo {
    background: #fff;
    cursor: pointer;
    box-shadow: inset 0 0 0 2px;
    border: 4px solid #fff;
    width: 3rem;
    height: 3rem;
    border-radius: 100%;
    outline: none;
  }

  .quikpik-stop-media,
  .quikpik-record-media {
    position: relative;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    background: #f00;
    box-shadow: inset 0 0 0 2px;
    border: 4px solid #fff;
    width: 3rem;
    height: 3rem;
    border-radius: 100%;
    outline: none;
  }

  .quikpik-stop-media {
    background: transparent;
  }

  .quikpik-stop-media::before {
    content: '';
    background: #f00;
    height: 1.5rem;
    width: 1.5rem;
    border-radius: 2px;
  }

  .quikpik-snap-photo:focus {
    box-shadow: inset 0 0 0 4px;
  }

  .quikpik-media-retake,
  .quikpik-media-accept {
    background: #5a67d8;
    color: #fff;
    border: 0;
    padding: 0.5rem 0.75rem;
    font-size: 0.875rem;
    border-radius: 0.375rem;
    cursor: pointer;
    margin: 0 0.25rem;
    outline: none;
  }

  .quikpik-media-retake {
    border: 1px solid;
    background: transparent;
    color: inherit;
  }

  .quikpik-info {
    color: #6b7280;
    display: flex;
    align-items: center;
    justify-content: center;
  }
</style>
